### ISSUE TITLE
How to use it on Ubuntu 18.04

### ISSUE THREAD

**Issue by tdurand** [qzed/linux-surfacebook2-mshw0153#3]
Hello, 

Thanks for this, I want to be able to enable / disable my nvidia card .. I installed latest jake kernel patch... and then your module via `sudo make dkms-install`

But when I try to use it I get command not found

```bash 
tdurand@tdurand-Surface-Book-2:~$ dgpu_power_init
dgpu_power_init: command not found
```

I'm sure I'm not using it the they I should, maybe you can point me in the right direction

Thanks

**Comment by qzed** [comment]
@tdurand `dgpu_power_init` is the module parameter. If you want to set that, you need to do so via `modprobe.d` (similar as described [here](https://feeding.cloud.geek.nz/posts/linux-kernel-module-options-on-debian/) for the `i915` module). However, I don't recommend doing that, as certain desktop environments (Gnome) claim the device (during the DE's initialization phase), due to which the device cannot be disabled dynamically. Edit: by default, the dGPU is powered off when the module loads.

Instead, you may want to have a look at my [surface](https://github.com/qzed/linux-surface-control) command line utility (there are .deb packages for Ubuntu, too). With that, you can set the dGPU power-state via `sudo surface dgpu set <state>` where `<state>` is either on or off.

If you don't want to use this tool, you can also use the raw sysfs interface, i.e. do something like
```
echo on | sudo tee /sys/bus/acpi/devices/MSHW0153:00/physical_node/dgpu_power
```

**Comment by tdurand** [comment]
Ok thanks, was on the wrong repo, will try your surface tool !

**Comment by qzed** [comment]
It was the right repo to post this. I've updated the documentation with a link to the `surface` tool and a bit more info.

**Comment by tdurand** [comment]
Seems this messed up my CUDA setup, I get this `no CUDA-capable device is detected` now.. I'll try to debug this and let you know

**Comment by qzed** [comment]
You currently need to manually load the driver after enabling the dGPU (edit: I think the best way to do this is the `nvidia-modprobe` command). Also, by default it is disabled, so you need to do this every time you restart the device.

**Comment by tdurand** [comment]
Ok ! Yes is re-enabled it after restart and it works now.
